[package]
name = "randar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
inquire = "0.7.5"
las = { version = "0.9.3", features = ["laz-parallel"] }
rand = "0.9.0"
tqdm = "0.7.0"
